on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build project
        run: |
          cd client
          npm run build

      - name: Run code style check
        run: |
          cd client
          npm run lint

      - name: Run tests
        run: |
          cd client
          npm test